name: CI

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        description: "GitHub repository of the mod"
      branch:
        required: false
        description: "Branch of the repository to use. Will use the default if unspecified"
      mods:
        required: true
        description: "PowerShell array (quote delimited, comma separated) of mod names to package"
      ue_version_tag:
        required: false
        description: "Release of UnrealEngine-CSS to use. Will use the latest if unspecified"
      wwise_sdk_version:
        required: true
      wwise_integration_version:
        required: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Cleanup
        run: Remove-Item * -Recurse -Force -Confirm:$false -ErrorAction Ignore

      - uses: actions/checkout@v3
        with:
          repository: satisfactorymodding/SatisfactoryModLoader
          path: SML
        
      - uses: actions/checkout@v3
        with:
          repository: ${{inputs.repo}}
          ref: ${{inputs.branch}}
          path: SML/Mods/mod

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
      
      - name: Setup Unreal Engine
        uses: mircearoata/satisfactory-modding-ue-action@master
        with:
          tag: ${{inputs.ue_version_tag}}
          token: ${{ secrets.ACCESS_TOKEN }}
        
      - name: Add Wwise
        run: |
          gh release download --repo mircearoata/wwise-cli -p "wwise-cli.exe"
          ./wwise-cli.exe download     --sdk-version "${{inputs.wwise_sdk_version}}"          --filter Packages=SDK --filter DeploymentPlatforms=Windows_vc140 --filter DeploymentPlatforms=Windows_vc150 --filter DeploymentPlatforms=Windows_vc160 --filter DeploymentPlatforms=Windows_vc170 --filter DeploymentPlatforms=Linux --filter DeploymentPlatforms=
          ./wwise-cli.exe integrate-ue --integration-version "${{inputs.wwise_integration_version}}"  --project "SML\FactoryGame.uproject"
        env:
          WWISE_EMAIL: ${{ secrets.WWISE_EMAIL }}
          WWISE_PASSWORD: ${{ secrets.WWISE_PASSWORD }}

      - name: Create VS project files
        run: |
          & "$Env:UE_ROOT\\Engine\\Build\\BatchFiles\\Build.bat" -projectfiles -project="$Env:GITHUB_WORKSPACE\\SML\\FactoryGame.uproject" -game -rocket -progres

      - name: Build for Shipping
        run: MSBuild.exe .\\SML\\FactoryGame.sln /p:Configuration="Shipping" /p:Platform="Win64" /t:"Games\FactoryGame"

      - name: Build for Development Editor
        run: MSBuild.exe .\\SML\\FactoryGame.sln /p:Configuration="Development Editor" /p:Platform="Win64" /t:"Games\FactoryGame"
        
      - name: Package Mod
        run: |
          foreach ($mod in ${{inputs.mods}}) {
            & "$Env:UE_ROOT\\Engine\\Build\\BatchFiles\\RunUAT.bat" -ScriptsForProject="$Env:GITHUB_WORKSPACE\\SML\\FactoryGame.uproject" PackagePlugin -Project="$Env:GITHUB_WORKSPACE\\SML\\FactoryGame.uproject" -PluginName="$mod"
          }

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-products
          path: SML\\Saved\\ArchivedPlugins\\Windows\\*
